import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React  from "react";
import StoreProvider from "./StoreProvider";
import { text } from "node:stream/consumers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute top-4 left-110">
          
           <StoreProvider>
          <h1>Habits</h1>
          {children}


          </StoreProvider></div>
        

          
      <div className="absolute top-80 left-110">
        <h4>Add new habits</h4>
<h4>Title</h4>
<input
autoComplete="off"
          type="text"
          id="title"
          placeholder="Add title"></input>
        
<h4>Description</h4>
<input
autoComplete="off"
          type="text"
          id="description"
          placeholder="Add description"></input>
        


</div>

<div className="absolute top-120 left-110 gap-x-1 max-w-[166px] rounded-[80px]">
<button >Add</button>
</div>
      
      </body>

      
    </html>
  );
}
